name: TestCode

on:
  push:
    paths:
      - 'run.sh'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.10

      - name: Build TrafficTest
        run: |
          go mod tidy
          go build -o TrafficTest
          chmod +x TrafficTest

      - name: Run run.sh
        run: |
          chmod +x ./run.sh
          ./run.sh
